add payroll deductions
osu-mist/servicenow-api pull request #42
Opened 2024-02-05 19:02 UTC by alex-marie-merino

2024-02-05 19:27 UTC, Ruefa requested changes
Overall looks good. Needs a few updates and the new contrib commit

2024-02-05 19:27 UTC, Ruefa commented on src/api-routes/servicenow/employees/{osuId}/deductions.js
> +import { serializeDeductions } from '../../../../serializers/deductions-serializer';
Dont need the `../` should work with just `db/oracledb/servicenow-dao`

2024-02-05 19:27 UTC, Ruefa commented on src/db/oracledb/servicenow-dao.js
> +    await connection.commit();
Need to check the result of the commit to make sure it was successful

2024-02-05 19:45 UTC, alex-marie-merino commented on src/db/oracledb/servicenow-dao.js
> +    await connection.commit();
Do you have an example of this? I was just copying the syntax Tso-Liang used for the other functions.

2024-02-06 17:02 UTC, Ruefa commented on src/db/oracledb/servicenow-dao.js
> +    await connection.commit();
You're right. Its probably fine how it is then.

2024-02-06 17:31 UTC, alex-marie-merino commented on src/api-routes/servicenow/employees/{osuId}/deductions.js
> +import { serializeDeductions } from '../../../../serializers/deductions-serializer';
Fixed

2024-02-06 18:53 UTC, Ruefa approved these changes

2024-02-06 18:58 UTC, merged